apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka-server
    group: com.calendario
  name: eureka-server
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: eureka-server
    group: com.calendario
  type: ClusterIP