apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eureka-server
    group: com.calendario
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
      group: com.calendario
  template:
    metadata:
      labels:
        app: eureka-server
        group: com.calendario
    spec:
      containers:
        - name: eureka-server
          image: asia.gcr.io/calendario-273709/microservices/eureka-server
          ports:
            - containerPort: 8080
