apiVersion: v1
kind: Service
metadata:
  labels:
    app: message-service
    group: com.calendario
  name: message-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: message-service
    group: com.calendario
  type: ClusterIP