apiVersion: v1
kind: Service
metadata:
  labels:
    app: zuul-gateway
    group: com.calendario
  name: zuul-gateway
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: zuul-gateway
    group: com.calendario
  type: LoadBalancer