apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: skaffold-zuul-gateway
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: asia.gcr.io/aashayein/calendario/microservices/zuul-gateway
      context: .
      jib:
        project: com.calendario:zuul-gateway
        type: maven

deploy:
  kubectl:
    manifests:
      - k8s-*