apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: config-server
    group: com.calendario
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
      group: com.calendario
  template:
    metadata:
      labels:
        app: config-server
        group: com.calendario
    spec:
      containers:
        - name: config-server
          image: asia.gcr.io/calendario-273709/microservices/config-server
          ports:
            - containerPort: 8080
