apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
    group: com.calendario
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
      group: com.calendario
  template:
    metadata:
      labels:
        app: rabbitmq
        group: com.calendario
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_USER
          value: calendario
        - name: RABBITMQ_DEFAULT_PASS
          value: calendario
        - name: RABBITMQ_DEFAULT_VHOST
          value: calendario_vhost
        name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
          name: internal
        - containerPort: 15672
          name: ui