apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
    group: com.calendario
  name: rabbitmq
spec:
  ports:
    - name: internal
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: ui
      port: 80
      targetPort: 15672
      protocol: TCP
  selector:
    app: rabbitmq
    group: com.calendario
  type: ClusterIP