apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth-server
    group: com.calendario
  name: oauth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth-server
      group: com.calendario
  template:
    metadata:
      labels:
        app: oauth-server
        group: com.calendario
    spec:
      containers:
        - name: oauth-server
          image: asia.gcr.io/calendario-273709/microservices/oauth-server
          ports:
            - containerPort: 8080
