apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: skaffold-oauth-server
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: asia.gcr.io/aashayein/calendario/microservices/oauth-server
      context: .
      jib:
        project: com.calendario:oauth-server
        type: maven

deploy:
  kubectl:
    manifests:
      - k8s-*