apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: skaffold-user-service
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: asia.gcr.io/aashayein/calendario/microservices/user-service
      context: .
      jib:
        project: com.calendario:user-service
        type: maven

deploy:
  kubectl:
    manifests:
      - k8s-*