spring:
  application:
    name: eureka-server
  security:
    user:
      name: eurekaserver
      password: eurekaserver
      roles:
      - ADMIN

server:
  port: 8030

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eurekaserver:eurekaserver@${eureka.instance.hostname}:${server.port}/eureka/
