apiVersion: v1
kind: Service
metadata:
  labels:
    app: zipkin
    group: com.calendario
  name: zipkin
spec:
  ports:
    - name: ui
      port: 8080
      targetPort: 9411
      protocol: TCP
  selector:
    app: zipkin
    group: com.calendario
  type: ClusterIP